language: cpp
compiler: gcc
os: linux
dist: xenial

branches:
  only:
  - test

matrix:
  include:
  - env: DIST=xenial MODE=safe
  - env: DIST=xenial MODE=unsafe

before_install:
  - sudo tools/install-deps-${DIST}-${MODE}.sh

install:
  - sudo tools/install.sh

script:
  - echo 'Running autotests ...' && echo -en 'travis_fold:start:script.1\\r'
  - tools/run-autotests.sh
  - echo -en 'travis_fold:end:script.1\\r'
  - tools/run-e2e-tests.sh $MODE
