language: cpp
compiler: gcc
os: linux

branches:
  only:
  - travis

jobs:
  include:
    - env: OS=ubuntu DIST=cosmic

before_install:
  - mkdir build
  cd build
  cmake -DCMAKE_BUILD_TYPE=Release ..
  make

