language: cpp
compiler: gcc
os: linux

services:
  - docker

branches:
  only:
  - master

matrix:
  include:
  - env: DIST=xenial MODE=safe
  - env: DIST=xenial MODE=unsafe
  - env: DIST=bionic MODE=unsafe

before_install:
  - NAME=qs-${MODE}-${DIST}
  - docker build -f Dockerfile.${NAME} -t ${NAME} .

install:
  - docker run -d --name ${NAME} -e LC_ALL="en_US.UTF-8" -e LANG="en_US.UTF-8" ${NAME} tail -f /dev/null
  - SH="docker exec -t ${NAME} bash -c"

script:
  - $SH "tools/run-autotests.sh"
  - $SH "tools/run-e2e-tests.sh $MODE"
